server:
  port: 8222

eureka:
  client:
    register-with-eureka: false

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/auth/**