server:
  port: 8222

eureka:
  client:
    register-with-eureka: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/auth/**
        - id: nutrition-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/nutrition/**
          filters:
            - name: AuthenticationFilter
        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthenticationFilter
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"