eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb://admin:1234@localhost:27017/fitplanner?authSource=admin

application:
  security:
    jwt:
      secret-key: 947e15d4a7720123d07add5a2ec242e1eeebf453d653551da537c8e45a33c771
      expiration: 86400000 # a day